export const MovieTypes = {
    MOVIE_PREFIX: 'MOVIE_',
    MOVIE_LOAD_SUCCESS: 'MOVIE_LOAD_SUCCESS',
    MOVIE_ADD_SUCCESS: 'MOVIE_ADD_SUCCESS',
    MOVIE_UPDATE_SUCCESS: 'MOVIE_UPDATE_SUCCESS',
    MOVIE_DELETE_SUCCESS: 'MOVIE_DELETE_SUCCESS',

    MOVIE_ADD_FAILED: 'MOVIE_ADD_FAILED',
    MOVIE_UPDATE_FAILED: 'MOVIE_UPDATE_FAILED',
    MOVIE_DELETE_FAILED: 'MOVIE_DELETE_FAILED',

};